### PR TITLE
Add more scaling configuration

### PR DESCRIPTION
**Pull request by jvisker**

### CODE REVIEW

**Comment by GaryGSC** [comment]
The implementation looks good because you've managed to do it in a semver-minor way, but now the description for `autoscaling_config` is confusing, since `autoscaling_config` is required to be non-null to make use of these new options that let us configure autoscaling policies and alarm.

It currently reads:
> Configuration for default autoscaling policies and alarms. Set to `null` if you want to set up your own autoscaling policies and alarms.

**Review by GaryGSC — DISMISSED** [review]
I'm fine to move forward with this if we create an issue to refactor in a future major-version release.

**Comment by jvisker** [comment]
> The implementation looks good because you've managed to do it in a semver-minor way, but now the description for `autoscaling_config` is confusing, since `autoscaling_config` is required to be non-null to make use of these new options that let us configure autoscaling policies and alarm.
> 
> It currently reads:
> 
> > Configuration for default autoscaling policies and alarms. Set to `null` if you want to set up your own autoscaling policies and alarms.

@GaryGSC  I'm fine still putting an issue on the repository for a future refactor, but I did add a clarifying sentence, which dismissed your approval.

**Review by GaryGSC — APPROVED** [review]
That's a bit better now. I'd still love to eventually refactor to make use of [optional object attributes](https://www.terraform.io/language/expressions/type-constraints#experimental-optional-object-type-attributes), once they finally make it out of experimental status.

**Comment by GaryGSC** [comment]
Especially [once they support defaults](https://github.com/hashicorp/terraform/pull/31154). 🙂

**Comment by jvisker** [comment]
@GaryGSC Yeah. I've been watching that feature. Unfortunately even when it does come out of experimental status it won't work with older versions of terraform.

**Pull request merged**
